## create schema
CREATE SCHEMA G3T9;
USE G3T9;


## create tables
CREATE TABLE MISSION (
ID INT NOT NULL PRIMARY KEY,
StartDateTime DATETIME NOT NULL, 
EndDateTime DATETIME NOT NULL,
Description VARCHAR(100)
);

CREATE TABLE AGENT (
EID INT NOT NULL PRIMARY KEY,
SecurityClearance INT NOT NULL,
IsPilot BOOLEAN NOT NULL,
IsOperator BOOLEAN NOT NULL
);

CREATE TABLE OPERATOR (
EID INT NOT NULL PRIMARY KEY,
OpLicense CHAR(8) NOT NULL UNIQUE,
ExpiryDate DATE NOT NULL,
OpCertificateID CHAR(8) NOT NULL,
CONSTRAINT OPERATOR_FK FOREIGN KEY (EID) REFERENCES AGENT(EID)
);

CREATE TABLE PILOT (
EID INT NOT NULL PRIMARY KEY,
PilotLicense CHAR(8) NOT NULL UNIQUE,
ExpiryDate DATE NOT NULL,
CONSTRAINT PILOT_FK FOREIGN KEY (EID) REFERENCES AGENT(EID)
);

CREATE TABLE DRONEGROUP (
ID INT NOT NULL,
OperatorEID INT NOT NULL,
PilotEID INT NOT NULL, 
CONSTRAINT DRONEGROUP_PK PRIMARY KEY (ID, OperatorEID, PilotEID),
CONSTRAINT DRONEGROUP_FK1 FOREIGN KEY (ID) REFERENCES MISSION(ID),
CONSTRAINT DRONEGROUP_FK2 FOREIGN KEY (OperatorEID) REFERENCES OPERATOR(EID),
CONSTRAINT DRONEGROUP_FK3 FOREIGN KEY (PilotEID) REFERENCES PILOT(EID)
);

CREATE TABLE DRONE (
ID INT NOT NULL PRIMARY KEY,
DroneModel VARCHAR(50) NOT NULL
);

CREATE TABLE GRPDRONES (
ID INT NOT NULL,
OperatorEID INT NOT NULL,
PilotEID INT NOT NULL, 
DroneID INT NOT NULL,
CONSTRAINT GRPDRONES_PK PRIMARY KEY (ID, OperatorEID, PilotEID, DroneID),
CONSTRAINT GRPDRONES_FK1 FOREIGN KEY (ID, OperatorEID, PilotEID) REFERENCES DRONEGROUP(ID, OperatorEID, PilotEID),
CONSTRAINT GRPDRONES_FK2 FOREIGN KEY (DroneID) REFERENCES DRONE(ID)
);

CREATE TABLE DRONECAMERA (
ID INT NOT NULL,
Number INT NOT NULL,
CameraModel VARCHAR(50) NOT NULL,
CONSTRAINT DRONECAMERA_PK PRIMARY KEY (ID, Number),
CONSTRAINT DRONECAMERA_FK FOREIGN KEY (ID) REFERENCES DRONE(ID)
);

CREATE TABLE CAMERA (
SerialNo INT NOT NULL PRIMARY KEY,
Model VARCHAR(15) NOT NULL,
Status VARCHAR(15) NOT NULL,
IsIP68 BOOLEAN NOT NULL
);

CREATE TABLE TRACKER (
ID INT NOT NULL PRIMARY KEY,
DisposeDate DATE NOT NULL,
AssignDate DATE NOT NULL,
DroneID INT,
CameraSN INT,
CONSTRAINT TRACKER_FK1 FOREIGN KEY (DroneID) REFERENCES DRONE(ID),
CONSTRAINT TRACKER_FK2 FOREIGN KEY (CameraSN) REFERENCES CAMERA(SerialNo)
);

CREATE TABLE RECORD (
TrackID INT NOT NULL,
DateTime DATETIME NOT NULL,
Latitude DOUBLE NOT NULL,
Longitude DOUBLE NOT NULL,
Altitude DOUBLE NOT NULL,
CONSTRAINT RECORD_PK PRIMARY KEY (TrackID, DateTime),
CONSTRAINT RECORD_FK FOREIGN KEY (TrackID) REFERENCES TRACKER(ID)
);

CREATE TABLE NEARBY (
ID INT NOT NULL,
TrackID INT NOT NULL,
DateTime DATETIME NOT NULL,
CONSTRAINT NEARBY_PK PRIMARY KEY (ID, TrackID, DateTime),
CONSTRAINT NEARBY_FK1 FOREIGN KEY (ID) REFERENCES TRACKER(ID),
CONSTRAINT NEARBY_FK2 FOREIGN KEY (TrackID, DateTime) REFERENCES RECORD(TrackID, DateTime)
);

CREATE TABLE PHOTO (
ID INT NOT NULL PRIMARY KEY,
DateTime DATETIME NOT NULL,
DroneID INT,
DroneCamNum INT,
CameraSN INT,
CONSTRAINT PHOTO_FK1 FOREIGN KEY (DroneID, DroneCamNum) REFERENCES DRONECAMERA(ID, Number),
CONSTRAINT PHOTO_FK2 FOREIGN KEY (CameraSN) REFERENCES CAMERA(SerialNo)
);

CREATE TABLE POI (
ID INT NOT NULL PRIMARY KEY,
Name VARCHAR(100)
);

CREATE TABLE PHOTOPOI (
PhotoID INT NOT NULL,
POIID INT NOT NULL,
Confidence DOUBLE NOT NULL,
CONSTRAINT PHOTOPOI_PK PRIMARY KEY (PhotoID, POIID),
CONSTRAINT PHOTOPOI_FK1 FOREIGN KEY (PhotoID) REFERENCES PHOTO(ID),
CONSTRAINT PHOTOPOI_FK2 FOREIGN KEY (POIID) REFERENCES POI(ID)
);

CREATE TABLE POIRELATION (
POI1 INT NOT NULL,
POI2 INT NOT NULL,
Description VARCHAR(100),
CONSTRAINT POIRELATION_PK PRIMARY KEY (POI1, POI2),
CONSTRAINT POIRELATION_FK1 FOREIGN KEY (POI1) REFERENCES POI(ID),
CONSTRAINT POIRELATION_FK2 FOREIGN KEY (POI2) REFERENCES POI(ID)
);


## load data from sample datafiles
LOAD DATA INFILE '/usr/local/mysql/data/mission.txt' INTO TABLE MISSION
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/agent.txt' INTO TABLE AGENT
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/operator.txt' INTO TABLE OPERATOR
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/pilot.txt' INTO TABLE PILOT
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/dronegroup.txt' INTO TABLE DRONEGROUP
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/drone.txt' INTO TABLE DRONE
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/grpdrones.txt' INTO TABLE GRPDRONES
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/dronecamera.txt' INTO TABLE DRONECAMERA
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/camera.txt' INTO TABLE CAMERA
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/tracker.txt' INTO TABLE TRACKER
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/record.txt' INTO TABLE RECORD
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/nearby.txt' INTO TABLE NEARBY
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/photo.txt' INTO TABLE PHOTO
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/poi.txt' INTO TABLE POI
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/photoPoi.txt' INTO TABLE PHOTOPOI
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

LOAD DATA INFILE '/usr/local/mysql/data/poiRelation.txt' INTO TABLE POIRELATION
FIELDS TERMINATED BY '\t' LINES TERMINATED BY
'\r\n' IGNORE 1 LINES;

